from typing import Any

from src.config.azure_models import get_chat_model


# ============================================================
# LLM
# ============================================================

llm = get_chat_model()


# ============================================================
# PROMPT
# ============================================================

REPORT_DRAFTER_PROMPT = """
You are a financial and competitive intelligence report writer.

Your job is to create an accurate, professional report using ONLY
the research evidence supplied to you.

IMPORTANT RULES:

1. Do NOT invent facts, numbers, percentages, dates, or sources.
2. Do NOT use outside knowledge.
3. Use ONLY the supplied research evidence as the factual basis.
4. If evidence is conflicting, explicitly mention the conflict.
5. If information is missing, say that the available evidence does
   not provide enough information.
6. Prefer precise financial figures from primary sources.
7. Distinguish between company-level metrics and segment-level metrics.
8. Do not confuse company revenue with segment revenue.
9. Preserve the fiscal year specified by the user when available.
10. Keep the report concise but informative.
11. Cite sources using the source information provided in the evidence.
12. Do not claim that a source says something unless that information
    is actually present in the supplied evidence.

The report should contain:

- Executive Summary
- Key Findings
- Detailed Analysis
- Source Evidence

For comparison questions, compare the companies explicitly and
highlight important differences.

For financial questions, clearly identify:

- Metric
- Fiscal year
- Value
- Year-over-year change when supported by evidence

Use professional business language.
"""


# ============================================================
# DRAFT REPORT
# ============================================================

def draft_report(
    question: str,
    analysis: str,
    research_context: str,
) -> str:
    """
    Generate the final report using the current LangGraph
    workflow state.

    Parameters
    ----------
    question:
        Original user question.

    analysis:
        Output generated by the Analysis Agent.

    research_context:
        Evidence collected by the Research Agent, including
        internal RAG, financial web search, and general web search.

    Returns
    -------
    str
        Final generated report.
    """

    if not question:
        raise ValueError(
            "Question cannot be empty."
        )

    if not analysis:
        raise ValueError(
            "Analysis cannot be empty."
        )

    if not research_context:
        research_context = (
            "No research evidence was available."
        )

    prompt = f"""
{REPORT_DRAFTER_PROMPT}


============================================================
ORIGINAL USER QUESTION
============================================================

{question}


============================================================
ANALYSIS AGENT OUTPUT
============================================================

{analysis}


============================================================
RESEARCH EVIDENCE
============================================================

{research_context}


============================================================
TASK
============================================================

Write the final financial / competitive intelligence report.

The report must be based ONLY on the supplied research evidence.

Use the Analysis Agent output as the analytical interpretation,
but verify factual claims against the supplied research evidence.

Do NOT introduce facts from your own knowledge.

For every important financial claim, preserve the source information
provided in the research evidence.

If the evidence does not contain enough information to support a
claim, explicitly say so.

For a company comparison:

1. Compare the companies directly.
2. Identify the relevant revenue figures or growth rates.
3. Clearly distinguish company-level revenue from segment revenue.
4. Identify the fiscal year when supported.
5. Explain which company had stronger or weaker growth only when
   the supplied evidence supports that conclusion.

Required structure:

# Executive Summary

# Key Findings

# Detailed Analysis

# Source Evidence

Keep the report professional, concise, and evidence-based.
"""

    try:

        response = llm.invoke(
            prompt
        )

        content = getattr(
            response,
            "content",
            response,
        )

        if isinstance(
            content,
            list,
        ):
            content = "\n".join(
                str(item)
                for item in content
            )

        return str(
            content
        ).strip()

    except Exception as exc:

        raise RuntimeError(
            "Report drafting failed: "
            f"{type(exc).__name__}: {exc}"
        ) from exc


# ============================================================
# REPORT DRAFTER AGENT
# ============================================================

def report_drafter(
    research: dict[str, Any],
) -> dict[str, Any]:
    """
    Compatibility wrapper for standalone usage.

    This allows the report drafter to work with the older
    research dictionary format as well as the current workflow.
    """

    print()
    print("=" * 70)
    print("REPORT DRAFTER AGENT")
    print("=" * 70)

    question = research.get(
        "question",
        "",
    )

    analysis = research.get(
        "analysis",
        "",
    )

    research_context = research.get(
        "research_context",
        "",
    )

    print()
    print("Preparing research evidence...")

    print(
        f"Question available: "
        f"{bool(question)}"
    )

    print(
        f"Analysis available: "
        f"{bool(analysis)}"
    )

    print(
        f"Research context available: "
        f"{bool(research_context)}"
    )

    print()
    print("Generating report...")

    report = draft_report(
        question=question,
        analysis=analysis,
        research_context=research_context,
    )

    result = {
        "report": report,
        "companies": research.get(
            "companies",
            [],
        ),
        "intent": research.get(
            "intent",
            "",
        ),
        "fiscal_year": research.get(
            "fiscal_year",
            "",
        ),
    }

    print()
    print("Report generated successfully.")

    return result


# ============================================================
# PRINT REPORT
# ============================================================

def print_report(
    result: dict[str, Any],
) -> None:
    """
    Print the final report.
    """

    print()
    print("=" * 70)
    print("FINAL REPORT")
    print("=" * 70)

    report = result.get(
        "report",
        "",
    )

    print()
    print(report)

    print()
    print("=" * 70)


# ============================================================
# STANDALONE TEST
# ============================================================

if __name__ == "__main__":

    question = (
        "Compare Microsoft and NVIDIA revenue growth."
    )

    print()
    print("#" * 70)
    print("REPORT DRAFTER TEST")
    print("#" * 70)

    print()
    print(
        "This module is intended to be executed "
        "through the LangGraph workflow."
    )

    print()
    print(
        "Run:"
    )

    print(
        "python -m src.graph.workflow"
    )